name: "Regression testing"

on:
  push:
    branches: ["main"]

jobs:
  functional_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Set up Python and Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r packages.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run tests
        run: pytest --alluredir=./allure-results --browser_name chrome --tracing=retain-on-failure

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-traces
          path: test-results/