name: "Regression testing"

on:
  push:
    branches: ["main"]

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: Pull code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run your tests
      run: pytest --alluredir=./allure-results --browser_name chrome --tracing=retain-on-failure

    - name: Generate Allure report
      run: npm install -g allure-commandline --save-dev allure generate ./allure-results --clean -o ./allure-report

    - name: Upload Allure HTML report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/

    - name: Upload Playwright traces
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/