name: "Regression and Performance Testing"

on:
  push:
    branches: ["main"]

jobs:
  # JOB 1: Pruebas funcionales con Playwright y Pytest
  functional_testing:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.12'
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y allure

      - name: Install Node.js packages (including Lighthouse)
        run: npm install

      - name: Install Python dependencies
        run: pip install -r packages.txt

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run functional tests
        run: pytest --alluredir=./allure-results --browser_name chrome --tracing=retain-on-failure

      - name: Generate Allure report  
        uses: simple-elf/allure-report-action@v1.7  
        if: always()  
        with:  
          allure_results: allure-results  
          allure_history: allure-results

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/

  # JOB 2: Pruebas de rendimiento con Locust
  performance_testing:
    runs-on: ubuntu-latest
    # Si vuelves a habilitar el job 1, descomenta la siguiente línea
    # needs: functional_testing 
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.12'
      
      - name: Install Python dependencies
        run: pip install -r packages.txt

      - name: Run Locust performance test with 5% failure threshold
        run: |
          locust -f tests/performance/locustfile.py \
          --headless \
          --csv=locust-results \
          --html=locust-report.html \
          # --- Criterio de Aceptación Funcional ---
          # Falla si la tasa de errores (definidos por response.failure) es > 5%
          --check-fail-ratio 0.05

      - name: Upload Locust results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: locust-performance-report
          path: |
            locust-report.html
            locust-results*